[global/wm]
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/base]
monitor = ${env:MONITOR:}
width = 100%
height = 30px
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

bottom = true
line-size = 6pt
border-color = #00000000

padding-left = 0
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.flamingo}

font-0 = MesloLGS Nerd Font Mono:size=11;4

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

; Bar for monitor 1 (with eth and filesystem)
[bar/monitor1]
inherit = bar/base
modules-left = xworkspaces
modules-right = eth pulseaudio filesystem nvme-temp memory cpu cpu-temp gpu-temp date

; Bar for monitor 2 (with battery)
[bar/monitor2]
inherit = bar/base
modules-left = xworkspaces
modules-right = eth pulseaudio filesystem nvme-temp memory cpu cpu-temp gpu-temp date

; Bar for monitor 3 (with battery)
[bar/monitor3]
inherit = bar/base
modules-left = xworkspaces
modules-right = eth pulseaudio filesystem nvme-temp memory cpu cpu-temp gpu-temp date

[settings]
screenchange-reload = true
pseudo-transparency = true
